// generated by agentic-setup adopt — the deliberate red of the adoption pull request.
// It fails on the base, where none of the adoption exists, and passes here.
// `ci/negative-control.mts` copies it onto a checkout of the base and requires
// that run to be red: a pull request whose generated checks cannot prove
// themselves is an adoption nobody should trust. Regenerate it with
// `node scripts/adopt.mts --pr`; it is a normal test file once this is merged.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';

const RECORD = "agentic.config.json";
const WORKFLOW = ".github/workflows/agentic-checks.yml";
const CHECKS = ["scope","negative-control","test"];
const TEST_COMMAND = "npm test";
const GENERATED_BY = "agentic-setup/adopt";

test('the adoption record every generated step reads is there', () => {
  assert.ok(existsSync(RECORD), RECORD + " is missing: the adoption record is what the generated steps read.");
  const record = JSON.parse(readFileSync(RECORD, 'utf8'));
  assert.equal(record.generatedBy, GENERATED_BY);
  assert.equal(record.commands.test, TEST_COMMAND);
});

test('the generated workflow runs every check the adoption records', () => {
  assert.ok(existsSync(WORKFLOW), WORKFLOW + " is missing: nothing would run the checks the merge gate requires.");
  const workflow = readFileSync(WORKFLOW, 'utf8');
  for (const name of CHECKS) {
    assert.ok(workflow.includes("\n  " + name + ":"), WORKFLOW + " declares no `" + name + "` job.");
  }
});
